### ISSUE TITLE
[Other issue]: Simulate laser scan in Gazebo

### ISSUE THREAD

**Issue by Jerrybaoyilei** [open-rmf/rmf_obstacle#23] opened 2024-03-21 15:46 UTC
### Before proceeding, is there an existing issue or discussion for this?

- [X] I have done a search for similar [issues](.?q=type%3Aissue) and [discussions](https://github.com/open-rmf/rmf/discussions).

### Description

Hi @Yadunund , I am quite new to ROS 2 and Open-RMF. 

I was trying to implement the `rmf_obstacle_detector_laserscan` package into the `rmf_demos` package. I also followed your instructions in #15 . Now in my terminal I can see "[INFO] [1711031152.446753857] [laserscan_obstacle_detector]: Activation successful. Waiting to receive 10 LaserScan messages on topic lidar/scan to begin calibration.", but since I don't have any simulated laser scanner in my gazebo simulation, there is currently no LaserScan message published to this lidar/scan topic.

I wonder which simulated laser scanner package did you use in achieving the deep blue laser scan result in [the gif you showed in Readme](https://github.com/open-rmf/rmf_obstacle/blob/media/rmf_obstacle_detector_laserscan.gif)? I've checked in Gazebo Classic tutorials, and the laser scan plugin are attached to a robot, whereas the one in this gif looks like a stationary one, which is what I hope to use. Thank you very much!

**Comment by Yadunund** [comment] 2024-03-25 02:20
Hi @Jerrybaoyilei,

You'll need to add a lidar model to your .world file or spawn it into the world. ie, just as you would attach a lidar model to one of your robot links through a fixed joint, you could need to instead create a fixed joint between the model and the `world`. Hope that clarifies. Since this is not a bug i'll close this ticket but feel free to reopen otherwise. If you're planning to submit a GSoC proposal, there is a line item in #22 related to `rmf_demos` where the goal would be to spawn such sensors in a demo world as part of a end-to-end simulation of the obstacle detection pipeline.

**Closed by Yadunund** 2024-03-25 02:20 UTC

**Comment by Jerrybaoyilei** [comment] 2024-03-25 02:46
Hi @Yadunund , thank you for the clarification! From my understanding, attaching a lidar model to the robot won't work with this package, right? Since the "obstacle-free" basis world is created from the first 10 LaserScan messages (please correct me if I am wrong)

I am not submitting a GSoC proposal. I am just exploring open-rmf and trying out the simulations (thank you and your team for building this amazing platform)

Also, I apologize that I asked the question here even though it's not a bug. It's just I couldn't find much information online regarding this package, and I figured maybe I could ask here directly...

**Comment by Jerrybaoyilei** [comment] 2024-04-03 23:30
Hi @Yadunund , I used the `ros_gz_bridge` you mentioned in the other ticket. Then I realized that it no longer works with Gazebo Classic (which is what I've been using). Therefore, I had to reconstruct the LiDAR model for Ignition Gazebo 6 (Fortress) based on [this Gazebo tutorial](https://gazebosim.org/docs/harmonic/sensors)

However, even though I successfully got some data reading from echoing the converted ROS 2 topics, the LiDAR has an intensity of 0 and I cannot see any rays in Ignition Gazebo. I wonder if you used some version of the `ros_gz_bridge` that works with Gazebo classic and ROS 2? Since the gif in the readme of this package looks like Gazebo classic. Thank you!

**Comment by Yadunund** [comment] 2024-04-04 02:51
It's best to stick to Gazebo (new) as Gazebo Classic (old) will be retired soon. With the new Gazebo, you'll need to explictly add a plugin in the world sdf to visualize the lidar rays. See https://github.com/gazebosim/gz-sim/blob/b9138fb12b0cef77621ed3a5eba577ebe4f7abd0/examples/worlds/visualize_lidar.sdf#L125-L126

Regarding intensities, you'll need to check whether the lidar plugin in Gazebo supports this. Even if it did, I assume it would be conditioned on every asset in the gazebo world properly defining PBR parameters. https://github.com/gazebosim/gz-sensors/blob/gz-sensors8/include/gz/sensors/GpuLidarSensor.hh

Usually, relying on the [range values](https://github.com/ros2/common_interfaces/blob/5b8223134c79642e86057d7444e65a2c3cd54b70/sensor_msgs/msg/LaserScan.msg#L26) is sufficient.

**Comment by Jerrybaoyilei** [comment] 2024-04-04 14:12
@Yadunund Got it. Thank you! 

Also, is there a historical version of this package (rmf_obstacle) that works with Humble binaries of ROS 2 and rmf that I can use? I am asking only because I modified some code when I was using ROS 2 Humble and the humble binary of rmf, and some of these packages were significantly changed in ROS 2 Iron. Thank you!

**Comment by Yadunund** [comment] 2024-04-06 10:21
There isn't. Since this package is not stabilized yet, there are no distro branches associated with it.

**Comment by Jerrybaoyilei** [comment] 2024-04-08 15:15
Got it, thank you!

**Comment by Jerrybaoyilei** [comment] 2024-04-09 04:19
Hi @Yadunund , sorry to bother you with yet another question. I got the LiDAR showing up in GUI and laser detector working (I can see the terminal output indicating there are obstacles detected). But when I tried to run `ros2 run rmf_obstacle_ros2 lane_blocker_node` and then add an obstacle in Ignition Gazebo 6, I got the following in the terminal:
```
[INFO] [1712633404.831764106] [lane_blocker_node]: Message Filter dropping message: frame 'VelodyneHDL-32/top/gpu_lidar' at time 0.000 for reason 'the timestamp on the message is earlier than all the data in the transform cache'
```
Have you encountered this before? I am using ROS 2 Iron (binary installation) and rmf iron-release branch (binary installation)

**Comment by Yadunund** [comment] 2024-04-09 07:51
Are you piping the `/clock` topic via the ros_gz_bridge node? This is to synchronize th time between the Gz simulation and the ROS nodes, else the latter will be using the current system time.

**Comment by Yadunund** [comment] 2024-04-10 11:59
Did you pass `use_sim_time: True` as ROS parameter to all your nodes?

**Comment by Jerrybaoyilei** [comment] 2024-04-10 17:33
No I didn't, not all nodes. I just changed the default value of `use_sim_time` to `True` in launch files in `rmf_demos`, but I discovered that some nodes still have `use_sim_time: False`, for example, `coke ingestor`
